travis:
  secure:
    BINSTAR_TOKEN: erH0D1pJUHMIy4lC1eqycC3T78QKnLBxXUayGlz3q5f4lgZKQmI4AEbarB6CzrKR743KMQknvNpMpDFj/UKFdleopINKsR9i97zpcXM6wqCaHRvXN4jADxvSxw56XY5T8a5Df6HnKYB1Ll22ownJ/cW8iYcZQjJ3jU5LwR8pVNvpdSSKNetWEVp0Q7sCAuWvM+3tCqsz9uISu94+Sk/8pGfMmls7B5IQM/DeOzPl3pJ8Y699GNj5WlZ/Mru5TM9sbki0U0NZ8w9ZOeH8RcZfY2vS41QfNkgCriTZKVKv4QO1RXAgyTvpPVGNG2nReTWHU495EBKGhkFcQj/are+hQjVHM3FihGxx97fo6CrokrsCxhvLhflfeHHQz1SYgPmTv34oQFKK9GzuxjGa6VqG7uv4WZJaYimkj+pdltfj94DAYafoWjVl07fVUUY/mfXloYCIbEa9CIeXMVZJJ4yU+z1hRRNhSkydr8Wn9RiWMbX8IwVSAfLvrzU3B/lWtfIJ93RWKTkkk+wTbAX6ZdZ+CXrgDu83fM7ombMJppCj2J6sM/qOxaiDDJHdWIU5sblNjRQBma0MNae53gbXlReH4i2TGP4evpiQ9F43mYZEfCAzwDfpJJlpn60gW5sh3LFtd/vRD6PpuMIXi4RIrkADDm/w7mHFDK9qHVkmiMnNhjI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
